Metrics/ClassLength:
    CountComments: false
    Max: 9999
Metrics/LineLength:
    Max: 9999
Metrics/MethodLength:
    Max: 9999
Metrics/AbcSize:
    Max: 9999
Metrics/CyclomaticComplexity:
    Max: 9999
Metrics/PerceivedComplexity:
    Max: 9999
Style/Documentation:
    Enabled: false
Style/SpaceBeforeBlockBraces:
    EnforcedStyle: no_space
Style/RedundantSelf:
    Enabled: false
Style/WordArray:
    Enabled: false
